package com.mycompany.proyectovideoclub;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oscar.lara
 */

public class UIAdmin extends javax.swing.JFrame {

    private DefaultTableModel modeloTablaDistribuidorasPeliculas;
    private JTable tablaDistribuidorasPeliculas;
    
    private DefaultTableModel modeloTablaDistribuidorasVideojuegos;
    private JTable tablaDistribuidorasVideojuegos;
    
    private DefaultTableModel modeloTablaFormatos;
    private JTable tablaFormatos;

    /**
     * Creates new form UIAdmin
     */
    public UIAdmin() {
        initComponents();
        inicializarTablaDistribuidorasPeliculas();
        cargarDistribuidorasPeliculas();  // Cargar distribuidoras al iniciar
                
        inicializarTablaFormatos();
        cargarFormatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanelDistribuidoras = new javax.swing.JPanel();
        jScrollPaneDistribuidoraPeliculas = new javax.swing.JScrollPane();
        tfNuevaDisPeliculas = new javax.swing.JTextField();
        botonAñadirDisPeliculas = new javax.swing.JButton();
        botonNuevaPelicula = new javax.swing.JButton();
        botonNuevaPelicula1 = new javax.swing.JButton();
        botonEmpleados = new javax.swing.JButton();
        jPanelDistribuidorasPeliculas = new javax.swing.JPanel();
        jScrollPaneFormatos = new javax.swing.JScrollPane();
        botonAñadirDisVideojuegos = new javax.swing.JButton();
        tfNuevaDisVideojuegos = new javax.swing.JTextField();
        botonNuevoSocio = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPaneDistribuidoraPeliculas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tfNuevaDisPeliculas.setText("Nueva distribuidora");
        tfNuevaDisPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNuevaDisPeliculasActionPerformed(evt);
            }
        });

        botonAñadirDisPeliculas.setText("Añadir");
        botonAñadirDisPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirDisPeliculasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDistribuidorasLayout = new javax.swing.GroupLayout(jPanelDistribuidoras);
        jPanelDistribuidoras.setLayout(jPanelDistribuidorasLayout);
        jPanelDistribuidorasLayout.setHorizontalGroup(
            jPanelDistribuidorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDistribuidorasLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelDistribuidorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDistribuidorasLayout.createSequentialGroup()
                        .addComponent(botonAñadirDisPeliculas)
                        .addGap(18, 18, 18)
                        .addComponent(tfNuevaDisPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneDistribuidoraPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanelDistribuidorasLayout.setVerticalGroup(
            jPanelDistribuidorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDistribuidorasLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPaneDistribuidoraPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelDistribuidorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNuevaDisPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAñadirDisPeliculas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonNuevaPelicula.setText("Agregar película");
        botonNuevaPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirGestionPeliculasModal(evt);
            }
        });

        botonNuevaPelicula1.setText("Consultar");
        botonNuevaPelicula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaPelicula1abrirGestionPeliculasModal(evt);
            }
        });

        botonEmpleados.setText("Empleados");
        botonEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirGestionEmpleadosModal(evt);
            }
        });

        botonAñadirDisVideojuegos.setText("Añadir");
        botonAñadirDisVideojuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirDisVideojuegosActionPerformed(evt);
            }
        });

        tfNuevaDisVideojuegos.setText("Nuevo formato");
        tfNuevaDisVideojuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNuevaDisVideojuegosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDistribuidorasPeliculasLayout = new javax.swing.GroupLayout(jPanelDistribuidorasPeliculas);
        jPanelDistribuidorasPeliculas.setLayout(jPanelDistribuidorasPeliculasLayout);
        jPanelDistribuidorasPeliculasLayout.setHorizontalGroup(
            jPanelDistribuidorasPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDistribuidorasPeliculasLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(botonAñadirDisVideojuegos)
                .addGap(30, 30, 30)
                .addComponent(tfNuevaDisVideojuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDistribuidorasPeliculasLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jScrollPaneFormatos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanelDistribuidorasPeliculasLayout.setVerticalGroup(
            jPanelDistribuidorasPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDistribuidorasPeliculasLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPaneFormatos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelDistribuidorasPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNuevaDisVideojuegos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAñadirDisVideojuegos))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        botonNuevoSocio.setText("Añadir socio");
        botonNuevoSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirGestionSociosModal(evt);
            }
        });

        jMenu1.setText("Salir");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelDistribuidoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanelDistribuidorasPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonEmpleados)
                    .addComponent(botonNuevaPelicula))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botonNuevaPelicula1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(botonNuevoSocio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDistribuidorasPeliculas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDistribuidoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevaPelicula)
                    .addComponent(botonNuevaPelicula1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEmpleados)
                    .addComponent(botonNuevoSocio))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Inicializar tabla para mostrar distribuidoras
    private void inicializarTablaDistribuidorasPeliculas() {
        modeloTablaDistribuidorasPeliculas = new DefaultTableModel(new String[]{"ID", "Nombre"}, 0);
        tablaDistribuidorasPeliculas = new JTable(modeloTablaDistribuidorasPeliculas);
        jScrollPaneDistribuidoraPeliculas.setViewportView(tablaDistribuidorasPeliculas);
    }

    // Cargar distribuidoras desde la base de datos y mostrarlas en la tabla
    private void cargarDistribuidorasPeliculas() {
        try (Connection conn = Database.getConnection()) {
            List<DistribuidoraPeliculas> distribuidoras = DistribuidoraPeliculas.consultarDistribuidorasPeliculas(conn);
            modeloTablaDistribuidorasPeliculas.setRowCount(0);  // Limpiar tabla antes de agregar
            for (DistribuidoraPeliculas d : distribuidoras) {
                modeloTablaDistribuidorasPeliculas.addRow(new Object[]{d.getId(), d.getNombre()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar distribuidoras: " + ex.getMessage());
        }
    }
    
    private void inicializarTablaFormatos() {
        modeloTablaFormatos = new DefaultTableModel(new String[]{"ID", "Nombre", "Cantidad de Productos"}, 0);
        tablaFormatos = new JTable(modeloTablaFormatos);
        jScrollPaneFormatos.setViewportView(tablaFormatos);
    }

    private void cargarFormatos() {
        List<Formato> formatos = Formato.obtenerFormatos();
        modeloTablaFormatos.setRowCount(0); // Limpiar la tabla antes de agregar datos

        for (Formato formato : formatos) {
            modeloTablaFormatos.addRow(new Object[]{
                formato.getId(), 
                formato.getNombre(), 
                formato.getCantidadProductos()
            });
        }
    }
    
    


    // Cargar distribuidoras desde la base de datos y mostrarlas en la tabla
//    private void cargarDistribuidorasVideojuegos() {
//        try (Connection conn = Database.getConnection()) {
//            List<DistribuidoraVideojuegos> distribuidoras = DistribuidoraVideojuegos.consultarDistribuidorasVideojuegos(conn);
//            modeloTablaDistribuidorasVideojuegos.setRowCount(0);  // Limpiar tabla antes de agregar
//            for (DistribuidoraVideojuegos d : distribuidoras) {
//                modeloTablaDistribuidorasVideojuegos.addRow(new Object[]{d.getId(), d.getNombre()});
//            }
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(this, "Error al cargar distribuidoras: " + ex.getMessage());
//        }
//    }

    // Agregar una nueva distribuidora al presionar el botón Añadir
    private void agregarDistribuidoraPeliculas() {
        String nombreDistribuidora = tfNuevaDisPeliculas.getText().trim();
        if (!nombreDistribuidora.isEmpty()) {
            try (Connection conn = Database.getConnection()) {
                DistribuidoraPeliculas.agregarDistribuidoraPeliculas(conn, nombreDistribuidora);
                cargarDistribuidorasPeliculas();  // Recargar lista
                tfNuevaDisPeliculas.setText("");  // Limpiar campo
                JOptionPane.showMessageDialog(this, "Distribuidora agregada con éxito.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al agregar distribuidora: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre de la distribuidora.");
        }
    }

    private void tfNuevaDisPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNuevaDisPeliculasActionPerformed
        agregarDistribuidoraPeliculas();
    }//GEN-LAST:event_tfNuevaDisPeliculasActionPerformed

    private void botonAñadirDisPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirDisPeliculasActionPerformed
        agregarDistribuidoraPeliculas();
    }//GEN-LAST:event_botonAñadirDisPeliculasActionPerformed

    private void abrirGestionPeliculasModal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirGestionPeliculasModal
        GestionPeliculas gestionPeliculas = new GestionPeliculas();
        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Gestión de Películas", true);
        dialog.setContentPane(gestionPeliculas.getContentPane());
        dialog.pack();
        dialog.setLocationRelativeTo(this);  // Centrar sobre la ventana principal
        dialog.setVisible(true);  // Mostrar modal
    }//GEN-LAST:event_abrirGestionPeliculasModal

    private void abrirGestionEmpleadosModal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirGestionEmpleadosModal
        GestionEmpleados1 gestionEmpleados = new GestionEmpleados1();
        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Gestión de Empleados", true);
        dialog.setContentPane(gestionEmpleados.getContentPane());
        dialog.pack();
        dialog.setLocationRelativeTo(this);  // Centrar sobre la ventana principal
        dialog.setVisible(true);  // Mostrar modal
    }//GEN-LAST:event_abrirGestionEmpleadosModal

//        private void abrirGestionSociosModal(java.awt.event.ActionEvent evt) {                                            
//        GestionSocios gestionSocios = new GestionSocios();
//        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Nuevo Socio", true);
//        dialog.setContentPane(gestionSocios.getContentPane());
//        dialog.pack();
//        dialog.setLocationRelativeTo(this);  // Centrar sobre la ventana principal
//        dialog.setVisible(true);  // Mostrar modal
//    }       
    // Agregar una nueva distribuidora al presionar el botón Añadir
    private void agregarDistribuidoraVideojuegos() {
        String nombreDistribuidora = tfNuevaDisVideojuegos.getText().trim();
        if (!nombreDistribuidora.isEmpty()) {
            try ( Connection conn = Database.getConnection()) {
                DistribuidoraVideojuegos.agregarDistribuidoraVideojuegos(conn, nombreDistribuidora);
                cargarDistribuidorasPeliculas();  // Recargar lista
                tfNuevaDisVideojuegos.setText("");  // Limpiar campo
                JOptionPane.showMessageDialog(this, "Distribuidora agregada con éxito.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al agregar distribuidora: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre de la distribuidora.");
        }
    }

    private void tfNuevaDisVideojuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNuevaDisVideojuegosActionPerformed
        agregarDistribuidoraVideojuegos();
    }//GEN-LAST:event_tfNuevaDisVideojuegosActionPerformed

    private void botonAñadirDisVideojuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirDisVideojuegosActionPerformed
        agregarDistribuidoraVideojuegos();
    }//GEN-LAST:event_botonAñadirDisVideojuegosActionPerformed

    private void botonNuevaPelicula1abrirGestionPeliculasModal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaPelicula1abrirGestionPeliculasModal
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNuevaPelicula1abrirGestionPeliculasModal

    private void abrirGestionSociosModal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirGestionSociosModal
        GestionSocios gestionSocios = new GestionSocios();
        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Nuevo Socio", true);
        dialog.setContentPane(gestionSocios.getContentPane());
        dialog.pack();
        dialog.setLocationRelativeTo(this);  // Centrar sobre la ventana principal
        dialog.setVisible(true);  // Mostrar modal
    }//GEN-LAST:event_abrirGestionSociosModal



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadirDisPeliculas;
    private javax.swing.JButton botonAñadirDisVideojuegos;
    private javax.swing.JButton botonEmpleados;
    private javax.swing.JButton botonNuevaPelicula;
    private javax.swing.JButton botonNuevaPelicula1;
    private javax.swing.JButton botonNuevoSocio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanelDistribuidoras;
    private javax.swing.JPanel jPanelDistribuidorasPeliculas;
    private javax.swing.JScrollPane jScrollPaneDistribuidoraPeliculas;
    private javax.swing.JScrollPane jScrollPaneFormatos;
    private javax.swing.JTextField tfNuevaDisPeliculas;
    private javax.swing.JTextField tfNuevaDisVideojuegos;
    // End of variables declaration//GEN-END:variables
}
