package com.mycompany.proyectovideoclub;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oscar.lara
 */

public class UIAdmin extends JFrame {

    private DefaultTableModel tableModel;
    private List<String> rutasImagenes;

 public UIAdmin() {
        setTitle("Listado de Alquileres en Curso");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(300, 300);

        // Llama a los componentes generados automáticamente
        initComponents();
        setLocationRelativeTo(null); // Abrir centrado en la pantalla, debe ir después de initComponents

        // Sobrescribe configuraciones personalizadas
        inicializarComponentes();
    }

    private void inicializarComponentes() {
             
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detallesDialog = new javax.swing.JDialog();
        btnCargarEmpleados = new javax.swing.JButton();
        btnCargarSocios = new javax.swing.JButton();
        menuAdmin = new javax.swing.JMenuBar();
        jMenuOpciones = new javax.swing.JMenu();

        javax.swing.GroupLayout detallesDialogLayout = new javax.swing.GroupLayout(detallesDialog.getContentPane());
        detallesDialog.getContentPane().setLayout(detallesDialogLayout);
        detallesDialogLayout.setHorizontalGroup(
            detallesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        detallesDialogLayout.setVerticalGroup(
            detallesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCargarEmpleados.setText("Ir a Empleados");
        btnCargarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarEmpleadosActionPerformed(evt);
            }
        });

        btnCargarSocios.setText("Ir a Socios");
        btnCargarSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarSociosActionPerformed(evt);
            }
        });

        jMenuOpciones.setText("Opciones");
        menuAdmin.add(jMenuOpciones);
        javax.swing.JMenuItem volverMenuItem = new javax.swing.JMenuItem("Cerrar sesión");
        volverMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Llamar al método de Utilidades para volver a la pantalla de Login
                Utilidades.volverALogin(UIAdmin.this);  // 'this' es la ventana actual (UIAdmin)
            }
        });

        // Agregar el JMenuItem al JMenu
        jMenuOpciones.add(volverMenuItem);

        // Agregar el JMenu a la barra de menús (suponiendo que ya tienes el JMenuBar creado)
        menuAdmin.add(jMenuOpciones);

        setJMenuBar(menuAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCargarEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCargarSocios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnCargarEmpleados)
                .addGap(31, 31, 31)
                .addComponent(btnCargarSocios)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        CustomRoundedButton customModel = new CustomRoundedButton();
        customModel.setNormalColor(Color.BLACK);
        customModel.setHoverColor(Color.DARK_GRAY);

        // Crear un botón estándar de Swing

        btnCargarEmpleados.setModel(customModel); // Asignar el modelo personalizado

        // Configurar colores dinámicamente con un MouseListener
        btnCargarEmpleados.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                btnCargarEmpleados.setBackground(customModel.getHoverColor());
            }

            @Override
            public void mouseExited(MouseEvent e) {
                btnCargarEmpleados.setBackground(customModel.getNormalColor());
            }
        });

        // Configurar el botón
        btnCargarEmpleados.setFocusPainted(false); // Quitar el borde de enfoque
        btnCargarEmpleados.setBackground(customModel.getNormalColor()); // Color inicial
        btnCargarEmpleados.setForeground(Color.WHITE); // Color del texto
        btnCargarEmpleados.setFont(new Font("Arial", Font.BOLD,16));
        CustomRoundedButton customModelSocios = new CustomRoundedButton();
        customModel.setNormalColor(Color.BLACK);
        customModel.setHoverColor(Color.DARK_GRAY);

        // Crear un botón estándar de Swing

        btnCargarSocios.setModel(customModelSocios); // Asignar el modelo personalizado

        // Configurar colores dinámicamente con un MouseListener
        btnCargarSocios.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                btnCargarSocios.setBackground(customModelSocios.getHoverColor());
            }

            @Override
            public void mouseExited(MouseEvent e) {
                btnCargarSocios.setBackground(customModelSocios.getNormalColor());
            }
        });

        // Configurar el botón
        btnCargarSocios.setFocusPainted(false); // Quitar el borde de enfoque
        btnCargarSocios.setBackground(customModelSocios.getNormalColor()); // Color inicial
        btnCargarSocios.setForeground(Color.WHITE); // Color del texto
        btnCargarSocios.setFont(new Font("Arial", Font.BOLD,16));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarEmpleadosActionPerformed
            UIEmpleado uiEmpleado = new UIEmpleado();
            uiEmpleado.setVisible(true);
    }//GEN-LAST:event_btnCargarEmpleadosActionPerformed

    private void btnCargarSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarSociosActionPerformed
            UISocio uiSocio = new UISocio();
            uiSocio.setVisible(true);
    }//GEN-LAST:event_btnCargarSociosActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String[] args) {
//        SwingUtilities.invokeLater(() -> {
//            UIAdmin ui = new UIAdmin();
//            ui.setVisible(true);
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarEmpleados;
    private javax.swing.JButton btnCargarSocios;
    private javax.swing.JDialog detallesDialog;
    private javax.swing.JMenu jMenuOpciones;
    private javax.swing.JMenuBar menuAdmin;
    // End of variables declaration//GEN-END:variables

}
