package com.mycompany.proyectovideoclub;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oscar.lara
 */
public class UIAdmin extends javax.swing.JFrame {

    private DefaultTableModel modeloTablaDistribuidorasPeliculas;
    private JTable tablaDistribuidorasPeliculas;
    
    private DefaultTableModel modeloTablaDistribuidorasVideojuegos;
    private JTable tablaDistribuidorasVideojuegos;
    
    private DefaultTableModel modeloTablaFormatos;
    private JTable tablaFormatos;

    /**
     * Creates new form UIAdmin
     */
    public UIAdmin() {
        initComponents();
        inicializarTablaDistribuidorasPeliculas();
        cargarDistribuidorasPeliculas();  // Cargar distribuidoras al iniciar
        
        inicializarTablaDistribuidorasVideojuegos();
        cargarDistribuidorasVideojuegos();
        
        inicializarTablaFormatos();
        cargarFormatos();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        botonEmpleados = new javax.swing.JButton();
        jScrollPaneDistribuidoraVideojuegos = new javax.swing.JScrollPane();
        jScrollPaneFormatos = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPaneDistribuidoraPeliculas = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        botonAñadirDisPeliculas = new javax.swing.JButton();
        tfNuevaDisPeliculas = new javax.swing.JTextField();
        tfNuevaDisVideojuegos = new javax.swing.JTextField();
        botonAñadirDisVideojuegos = new javax.swing.JButton();
        botonNuevaPelicula = new javax.swing.JButton();
        botonNuevaPelicula1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonEmpleados.setText("Empleados");
        botonEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirGestionEmpleadosModal(evt);
            }
        });

        jScrollPaneDistribuidoraPeliculas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneDistribuidoraPeliculas)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneDistribuidoraPeliculas, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );

        botonAñadirDisPeliculas.setText("Añadir");
        botonAñadirDisPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirDisPeliculasActionPerformed(evt);
            }
        });

        tfNuevaDisPeliculas.setText("Nueva distribuidora");
        tfNuevaDisPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNuevaDisPeliculasActionPerformed(evt);
            }
        });

        tfNuevaDisVideojuegos.setText("Nuevo formato");
        tfNuevaDisVideojuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNuevaDisVideojuegosActionPerformed(evt);
            }
        });

        botonAñadirDisVideojuegos.setText("Añadir");
        botonAñadirDisVideojuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirDisVideojuegosActionPerformed(evt);
            }
        });

        botonNuevaPelicula.setText("Agregar película");
        botonNuevaPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirGestionPeliculasModal(evt);
            }
        });

        botonNuevaPelicula1.setText("Consultar");
        botonNuevaPelicula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaPelicula1abrirGestionPeliculasModal(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonNuevaPelicula1)
                    .addComponent(botonNuevaPelicula)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNuevaDisPeliculas, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(tfNuevaDisVideojuegos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAñadirDisVideojuegos)
                            .addComponent(botonAñadirDisPeliculas))))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAñadirDisPeliculas)
                    .addComponent(tfNuevaDisPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAñadirDisVideojuegos)
                    .addComponent(tfNuevaDisVideojuegos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonNuevaPelicula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonNuevaPelicula1)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneDistribuidoraVideojuegos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPaneFormatos, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonEmpleados)
                                .addGap(20, 20, 20)))))
                .addGap(257, 257, 257))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEmpleados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPaneFormatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPaneDistribuidoraVideojuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Inicializar tabla para mostrar distribuidoras
    private void inicializarTablaDistribuidorasPeliculas() {
        modeloTablaDistribuidorasPeliculas = new DefaultTableModel(new String[]{"ID", "Nombre"}, 0);
        tablaDistribuidorasPeliculas = new JTable(modeloTablaDistribuidorasPeliculas);
        jScrollPaneDistribuidoraPeliculas.setViewportView(tablaDistribuidorasPeliculas);
    }

    // Cargar distribuidoras desde la base de datos y mostrarlas en la tabla
    private void cargarDistribuidorasPeliculas() {
        try ( Connection conn = DistribuidoraPeliculas.conectar()) {
            List<DistribuidoraPeliculas> distribuidoras = DistribuidoraPeliculas.consultarDistribuidorasPeliculas(conn);
            modeloTablaDistribuidorasPeliculas.setRowCount(0);  // Limpiar tabla antes de agregar
            for (DistribuidoraPeliculas d : distribuidoras) {
                modeloTablaDistribuidorasPeliculas.addRow(new Object[]{d.getId(), d.getNombre()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar distribuidoras: " + ex.getMessage());
        }
    }
    
    private void inicializarTablaFormatos() {
        modeloTablaFormatos = new DefaultTableModel(new String[]{"ID", "Nombre", "Cantidad de Productos"}, 0);
        tablaFormatos = new JTable(modeloTablaFormatos);
        jScrollPaneFormatos.setViewportView(tablaFormatos);
    }

    private void cargarFormatos() {
        List<Formato> formatos = Formato.obtenerFormatos();
        modeloTablaFormatos.setRowCount(0); // Limpiar la tabla antes de agregar datos

        for (Formato formato : formatos) {
            modeloTablaFormatos.addRow(new Object[]{
                formato.getId(), 
                formato.getNombre(), 
                formato.getCantidadProductos()
            });
        }
    }
    
    
        // Inicializar tabla para mostrar distribuidoras
    private void inicializarTablaDistribuidorasVideojuegos() {
        modeloTablaDistribuidorasVideojuegos = new DefaultTableModel(new String[]{"ID", "Nombre"}, 0);
        tablaDistribuidorasVideojuegos = new JTable(modeloTablaDistribuidorasVideojuegos);
        jScrollPaneDistribuidoraVideojuegos.setViewportView(tablaDistribuidorasVideojuegos);
    }

    // Cargar distribuidoras desde la base de datos y mostrarlas en la tabla
    private void cargarDistribuidorasVideojuegos() {
        try ( Connection conn = DistribuidoraPeliculas.conectar()) {
            List<DistribuidoraVideojuegos> distribuidoras = DistribuidoraVideojuegos.consultarDistribuidorasVideojuegos(conn);
            modeloTablaDistribuidorasVideojuegos.setRowCount(0);  // Limpiar tabla antes de agregar
            for (DistribuidoraVideojuegos d : distribuidoras) {
                modeloTablaDistribuidorasVideojuegos.addRow(new Object[]{d.getId(), d.getNombre()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar distribuidoras: " + ex.getMessage());
        }
    }

    // Agregar una nueva distribuidora al presionar el botón Añadir
    private void agregarDistribuidoraPeliculas() {
        String nombreDistribuidora = tfNuevaDisPeliculas.getText().trim();
        if (!nombreDistribuidora.isEmpty()) {
            try ( Connection conn = DistribuidoraPeliculas.conectar()) {
                DistribuidoraPeliculas.agregarDistribuidoraPeliculas(conn, nombreDistribuidora);
                cargarDistribuidorasPeliculas();  // Recargar lista
                tfNuevaDisPeliculas.setText("");  // Limpiar campo
                JOptionPane.showMessageDialog(this, "Distribuidora agregada con éxito.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al agregar distribuidora: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre de la distribuidora.");
        }
    }

    private void tfNuevaDisPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNuevaDisPeliculasActionPerformed
        agregarDistribuidoraPeliculas();
    }//GEN-LAST:event_tfNuevaDisPeliculasActionPerformed

    private void botonAñadirDisPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirDisPeliculasActionPerformed
        agregarDistribuidoraPeliculas();
    }//GEN-LAST:event_botonAñadirDisPeliculasActionPerformed

    private void abrirGestionPeliculasModal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirGestionPeliculasModal
        GestionPeliculas gestionPeliculas = new GestionPeliculas();
        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Gestión de Películas", true);
        dialog.setContentPane(gestionPeliculas.getContentPane());
        dialog.pack();
        dialog.setLocationRelativeTo(this);  // Centrar sobre la ventana principal
        dialog.setVisible(true);  // Mostrar modal
    }//GEN-LAST:event_abrirGestionPeliculasModal

    private void abrirGestionEmpleadosModal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirGestionEmpleadosModal
        GestionEmpleados gestionEmpleados = new GestionEmpleados();
        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Gestión de Empleados", true);
        dialog.setContentPane(gestionEmpleados.getContentPane());
        dialog.pack();
        dialog.setLocationRelativeTo(this);  // Centrar sobre la ventana principal
        dialog.setVisible(true);  // Mostrar modal
    }//GEN-LAST:event_abrirGestionEmpleadosModal

    // Agregar una nueva distribuidora al presionar el botón Añadir
    private void agregarDistribuidoraVideojuegos() {
        String nombreDistribuidora = tfNuevaDisVideojuegos.getText().trim();
        if (!nombreDistribuidora.isEmpty()) {
            try ( Connection conn = DistribuidoraVideojuegos.conectar()) {
                DistribuidoraVideojuegos.agregarDistribuidoraVideojuegos(conn, nombreDistribuidora);
                cargarDistribuidorasPeliculas();  // Recargar lista
                tfNuevaDisVideojuegos.setText("");  // Limpiar campo
                JOptionPane.showMessageDialog(this, "Distribuidora agregada con éxito.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al agregar distribuidora: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre de la distribuidora.");
        }
    }

    private void tfNuevaDisVideojuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNuevaDisVideojuegosActionPerformed
        agregarDistribuidoraVideojuegos();
    }//GEN-LAST:event_tfNuevaDisVideojuegosActionPerformed

    private void botonAñadirDisVideojuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirDisVideojuegosActionPerformed
        agregarDistribuidoraVideojuegos();
    }//GEN-LAST:event_botonAñadirDisVideojuegosActionPerformed

    private void botonNuevaPelicula1abrirGestionPeliculasModal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaPelicula1abrirGestionPeliculasModal
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNuevaPelicula1abrirGestionPeliculasModal



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadirDisPeliculas;
    private javax.swing.JButton botonAñadirDisVideojuegos;
    private javax.swing.JButton botonEmpleados;
    private javax.swing.JButton botonNuevaPelicula;
    private javax.swing.JButton botonNuevaPelicula1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneDistribuidoraPeliculas;
    private javax.swing.JScrollPane jScrollPaneDistribuidoraVideojuegos;
    private javax.swing.JScrollPane jScrollPaneFormatos;
    private javax.swing.JTextField tfNuevaDisPeliculas;
    private javax.swing.JTextField tfNuevaDisVideojuegos;
    // End of variables declaration//GEN-END:variables
}
