package com.mycompany.proyectovideoclub;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oscar.lara
 */

public class UIEmpleado extends javax.swing.JFrame {

    private DefaultTableModel modeloTablaDistribuidorasPeliculas;
    private JTable tablaDistribuidorasPeliculas;
    
    private DefaultTableModel modeloTablaDistribuidorasVideojuegos;
    private JTable tablaDistribuidorasVideojuegos;
    
    private DefaultTableModel modeloTablaFormatos;
    private JTable tablaFormatos;

    /**
     * Creates new form UIAdmin
     */
    public UIEmpleado() {
        initComponents();
        inicializarTablaDistribuidorasPeliculas();
        Utilidades.cargarImagenEnLabel(jLabelEmpleado, "images/empleado.png");
        cargarDistribuidorasPeliculas();  // Cargar distribuidoras al iniciar
        
        Utilidades.setPredefinedText(tfNuevaDisPeliculas, "Nueva distribuidora...");
        Utilidades.setPredefinedText(tfNuevoFormato, "Nuevo formato...");
        
        botonEmpleados.setVisible(false);
        
        inicializarTablaFormatos();
        cargarFormatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanelEmpleado = new javax.swing.JPanel();
        jLabelEmpleado = new javax.swing.JLabel();
        jPanelDistribuidoras = new javax.swing.JPanel();
        jScrollPaneDistribuidoraPeliculas = new javax.swing.JScrollPane();
        tfNuevaDisPeliculas = new javax.swing.JTextField();
        botonAñadirDisPeliculas = new javax.swing.JButton();
        jLabelTextoEmpleado = new javax.swing.JLabel();
        jPanelDistribuidorasPeliculas = new javax.swing.JPanel();
        jScrollPaneFormatos = new javax.swing.JScrollPane();
        botonAñadirDisVideojuegos = new javax.swing.JButton();
        tfNuevoFormato = new javax.swing.JTextField();
        jButtonRefresh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botonNuevaPelicula = new javax.swing.JButton();
        botonNuevoSocio = new javax.swing.JButton();
        botonEmpleados = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelEmpleado.setBackground(new java.awt.Color(204, 204, 255));
        jPanelEmpleado.setForeground(new java.awt.Color(204, 204, 255));

        jScrollPaneDistribuidoraPeliculas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tfNuevaDisPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNuevaDisPeliculasActionPerformed(evt);
            }
        });

        botonAñadirDisPeliculas.setText("Añadir");
        botonAñadirDisPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirDisPeliculasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDistribuidorasLayout = new javax.swing.GroupLayout(jPanelDistribuidoras);
        jPanelDistribuidoras.setLayout(jPanelDistribuidorasLayout);
        jPanelDistribuidorasLayout.setHorizontalGroup(
            jPanelDistribuidorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDistribuidorasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDistribuidorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDistribuidorasLayout.createSequentialGroup()
                        .addComponent(botonAñadirDisPeliculas)
                        .addGap(18, 18, 18)
                        .addComponent(tfNuevaDisPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneDistribuidoraPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanelDistribuidorasLayout.setVerticalGroup(
            jPanelDistribuidorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDistribuidorasLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPaneDistribuidoraPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDistribuidorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNuevaDisPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAñadirDisPeliculas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelTextoEmpleado.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabelTextoEmpleado.setText("Area del empleado");

        jScrollPaneFormatos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        botonAñadirDisVideojuegos.setText("Añadir");
        botonAñadirDisVideojuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirDisVideojuegosActionPerformed(evt);
            }
        });

        tfNuevoFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNuevoFormatoActionPerformed(evt);
            }
        });

        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDistribuidorasPeliculasLayout = new javax.swing.GroupLayout(jPanelDistribuidorasPeliculas);
        jPanelDistribuidorasPeliculas.setLayout(jPanelDistribuidorasPeliculasLayout);
        jPanelDistribuidorasPeliculasLayout.setHorizontalGroup(
            jPanelDistribuidorasPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDistribuidorasPeliculasLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanelDistribuidorasPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDistribuidorasPeliculasLayout.createSequentialGroup()
                        .addComponent(jButtonRefresh)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDistribuidorasPeliculasLayout.createSequentialGroup()
                        .addComponent(jScrollPaneFormatos, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDistribuidorasPeliculasLayout.createSequentialGroup()
                        .addComponent(botonAñadirDisVideojuegos)
                        .addGap(18, 18, 18)
                        .addComponent(tfNuevoFormato, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanelDistribuidorasPeliculasLayout.setVerticalGroup(
            jPanelDistribuidorasPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDistribuidorasPeliculasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneFormatos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDistribuidorasPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNuevoFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAñadirDisVideojuegos))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        botonNuevaPelicula.setText("Agregar película");
        botonNuevaPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirGestionPeliculasModal(evt);
            }
        });

        botonNuevoSocio.setText("Añadir socio");
        botonNuevoSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirGestionSociosModal(evt);
            }
        });

        botonEmpleados.setText("Empleados");
        botonEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirGestionEmpleadosModal(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonNuevoSocio)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonEmpleados)
                        .addGap(26, 26, 26)
                        .addComponent(botonNuevaPelicula)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevaPelicula)
                    .addComponent(botonEmpleados))
                .addGap(18, 18, 18)
                .addComponent(botonNuevoSocio)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelEmpleadoLayout = new javax.swing.GroupLayout(jPanelEmpleado);
        jPanelEmpleado.setLayout(jPanelEmpleadoLayout);
        jPanelEmpleadoLayout.setHorizontalGroup(
            jPanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpleadoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelEmpleadoLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jLabelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(56, 56, 56)
                            .addComponent(jLabelTextoEmpleado))
                        .addGroup(jPanelEmpleadoLayout.createSequentialGroup()
                            .addComponent(jPanelDistribuidoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanelDistribuidorasPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEmpleadoLayout.setVerticalGroup(
            jPanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEmpleadoLayout.createSequentialGroup()
                        .addComponent(jLabelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEmpleadoLayout.createSequentialGroup()
                        .addComponent(jLabelTextoEmpleado)
                        .addGap(32, 32, 32)))
                .addGroup(jPanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelEmpleadoLayout.createSequentialGroup()
                        .addComponent(jPanelDistribuidorasPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanelEmpleadoLayout.createSequentialGroup()
                        .addComponent(jPanelDistribuidoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanelDistribuidoras.setOpaque(false);
        jPanelDistribuidorasPeliculas.setOpaque(false);
        jPanel1.setOpaque(false);

        jMenu1.setText("Salir");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Inicializar tabla para mostrar distribuidoras
    private void inicializarTablaDistribuidorasPeliculas() {
        modeloTablaDistribuidorasPeliculas = new DefaultTableModel(new String[]{"ID", "Nombre"}, 0);
        tablaDistribuidorasPeliculas = new JTable(modeloTablaDistribuidorasPeliculas);
        jScrollPaneDistribuidoraPeliculas.setViewportView(tablaDistribuidorasPeliculas);
    }

    // Cargar distribuidoras desde la base de datos y mostrarlas en la tabla
    private void cargarDistribuidorasPeliculas() {
        try (Connection conn = Database.getConnection()) {
            List<DistribuidoraPeliculas> distribuidoras = DistribuidoraPeliculas.consultarDistribuidorasPeliculas(conn);
            modeloTablaDistribuidorasPeliculas.setRowCount(0);  // Limpiar tabla antes de agregar
            for (DistribuidoraPeliculas d : distribuidoras) {
                modeloTablaDistribuidorasPeliculas.addRow(new Object[]{d.getId(), d.getNombre()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar distribuidoras: " + ex.getMessage());
        }
    }
    
    private void inicializarTablaFormatos() {
        modeloTablaFormatos = new DefaultTableModel(new String[]{"ID", "Nombre", "Cantidad de Productos"}, 0);
        tablaFormatos = new JTable(modeloTablaFormatos);
        jScrollPaneFormatos.setViewportView(tablaFormatos);
    }

    private void cargarFormatos() {
        List<Formato> formatos = Formato.obtenerFormatos();
        modeloTablaFormatos.setRowCount(0); // Limpiar la tabla antes de agregar datos

        for (Formato formato : formatos) {
            modeloTablaFormatos.addRow(new Object[]{
                formato.getId(), 
                formato.getNombre(), 
                formato.getCantidadProductos()
            });
        }
    }
    
private void agregarFormatos() {
    String nombreFormato = tfNuevoFormato.getText().trim();  // Obtener el texto del campo de texto
    if (!nombreFormato.isEmpty()) {
        try (Connection conn = Database.getConnection()) {  // Establecer la conexión
            // Llamar al método agregarFormato
            Formato.agregarFormato(conn, nombreFormato);  
            cargarFormatos();  // Recargar lista de formatos
            tfNuevoFormato.setText("");  // Limpiar el campo de texto
            JOptionPane.showMessageDialog(this, "Formato agregado con éxito.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al agregar formato: " + ex.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Ingrese el nombre del formato.");
    }
}

    


    // Cargar distribuidoras desde la base de datos y mostrarlas en la tabla
//    private void cargarDistribuidorasVideojuegos() {
//        try (Connection conn = Database.getConnection()) {
//            List<DistribuidoraVideojuegos> distribuidoras = DistribuidoraVideojuegos.consultarDistribuidorasVideojuegos(conn);
//            modeloTablaDistribuidorasVideojuegos.setRowCount(0);  // Limpiar tabla antes de agregar
//            for (DistribuidoraVideojuegos d : distribuidoras) {
//                modeloTablaDistribuidorasVideojuegos.addRow(new Object[]{d.getId(), d.getNombre()});
//            }
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(this, "Error al cargar distribuidoras: " + ex.getMessage());
//        }
//    }

    // Agregar una nueva distribuidora al presionar el botón Añadir
    private void agregarDistribuidoraPeliculas() {
        String nombreDistribuidora = tfNuevaDisPeliculas.getText().trim();
        if (!nombreDistribuidora.isEmpty()) {
            try (Connection conn = Database.getConnection()) {
                DistribuidoraPeliculas.agregarDistribuidoraPeliculas(conn, nombreDistribuidora);
                cargarDistribuidorasPeliculas();  // Recargar lista
                tfNuevaDisPeliculas.setText("");  // Limpiar campo
                JOptionPane.showMessageDialog(this, "Distribuidora agregada con éxito.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al agregar distribuidora: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre de la distribuidora.");
        }
    }

    private void tfNuevaDisPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNuevaDisPeliculasActionPerformed
        agregarDistribuidoraPeliculas();
    }//GEN-LAST:event_tfNuevaDisPeliculasActionPerformed

    private void botonAñadirDisPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirDisPeliculasActionPerformed
        agregarDistribuidoraPeliculas();
    }//GEN-LAST:event_botonAñadirDisPeliculasActionPerformed

    private void abrirGestionPeliculasModal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirGestionPeliculasModal
        GestionPeliculas gestionPeliculas = new GestionPeliculas();
        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Gestión de Películas", true);
        dialog.setContentPane(gestionPeliculas.getContentPane());
        dialog.pack();
        dialog.setLocationRelativeTo(this);  // Centrar sobre la ventana principal
        dialog.setVisible(true);  // Mostrar modal
    }//GEN-LAST:event_abrirGestionPeliculasModal

    private void abrirGestionEmpleadosModal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirGestionEmpleadosModal
        GestionEmpleados1 gestionEmpleados = new GestionEmpleados1();
        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Gestión de Empleados", true);
        dialog.setContentPane(gestionEmpleados.getContentPane());
        dialog.pack();
        dialog.setLocationRelativeTo(this);  // Centrar sobre la ventana principal
        dialog.setVisible(true);  // Mostrar modal
    }//GEN-LAST:event_abrirGestionEmpleadosModal

//        private void abrirGestionSociosModal(java.awt.event.ActionEvent evt) {                                            
//        GestionSocios gestionSocios = new GestionSocios();
//        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Nuevo Socio", true);
//        dialog.setContentPane(gestionSocios.getContentPane());
//        dialog.pack();
//        dialog.setLocationRelativeTo(this);  // Centrar sobre la ventana principal
//        dialog.setVisible(true);  // Mostrar modal
//    }       
    // Agregar una nueva distribuidora al presionar el botón Añadir
    private void agregarDistribuidoraVideojuegos() {
        String nombreDistribuidora = tfNuevoFormato.getText().trim();
        if (!nombreDistribuidora.isEmpty()) {
            try ( Connection conn = Database.getConnection()) {
                DistribuidoraVideojuegos.agregarDistribuidoraVideojuegos(conn, nombreDistribuidora);
                cargarDistribuidorasPeliculas();  // Recargar lista
                tfNuevoFormato.setText("");  // Limpiar campo
                JOptionPane.showMessageDialog(this, "Distribuidora agregada con éxito.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al agregar distribuidora: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre de la distribuidora.");
        }
    }

    private void tfNuevoFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNuevoFormatoActionPerformed
        agregarDistribuidoraVideojuegos();
    }//GEN-LAST:event_tfNuevoFormatoActionPerformed

    private void botonAñadirDisVideojuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirDisVideojuegosActionPerformed
        agregarFormatos();
    }//GEN-LAST:event_botonAñadirDisVideojuegosActionPerformed

    private void abrirGestionSociosModal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirGestionSociosModal
        GestionSocios gestionSocios = new GestionSocios();
        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Nuevo Socio", true);
        dialog.setContentPane(gestionSocios.getContentPane());
        dialog.pack();
        dialog.setLocationRelativeTo(this);  // Centrar sobre la ventana principal
        dialog.setVisible(true);  // Mostrar modal
    }//GEN-LAST:event_abrirGestionSociosModal

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
         cargarFormatos();
    }//GEN-LAST:event_jButtonRefreshActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadirDisPeliculas;
    private javax.swing.JButton botonAñadirDisVideojuegos;
    private javax.swing.JButton botonEmpleados;
    private javax.swing.JButton botonNuevaPelicula;
    private javax.swing.JButton botonNuevoSocio;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabelEmpleado;
    private javax.swing.JLabel jLabelTextoEmpleado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDistribuidoras;
    private javax.swing.JPanel jPanelDistribuidorasPeliculas;
    private javax.swing.JPanel jPanelEmpleado;
    private javax.swing.JScrollPane jScrollPaneDistribuidoraPeliculas;
    private javax.swing.JScrollPane jScrollPaneFormatos;
    private javax.swing.JTextField tfNuevaDisPeliculas;
    private javax.swing.JTextField tfNuevoFormato;
    // End of variables declaration//GEN-END:variables
}
