package com.mycompany.proyectovideoclub;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oscar.lara
 */
public class UIEmpleado extends javax.swing.JFrame {

    private DefaultTableModel modeloTablaDistribuidorasPeliculas;
    private JTable tablaDistribuidorasPeliculas;

    private DefaultTableModel modeloTablaDistribuidorasVideojuegos;
    private JTable tablaDistribuidorasVideojuegos;

    private DefaultTableModel modeloTablaFormatos;
    private JTable tablaFormatos;

    /**
     * Creates new form UIAdmin
     */
    public UIEmpleado() {
        initComponents();
        setLocationRelativeTo(null); // Abrir centrado en la pantalla, debe ir después de initComponents

        inicializarTablaDistribuidorasPeliculas();
        Utilidades.cargarImagenEnLabel(jLabelEmpleado, "/images/empleado.png");
        cargarDistribuidorasPeliculas();  // Cargar distribuidoras al iniciar

        Utilidades.setPredefinedText(tfNuevaDisPeliculas, "Nueva distribuidora...");
        Utilidades.setPredefinedText(tfNuevoFormato, "Nuevo formato...");

        botonEmpleados.setVisible(false);

        inicializarTablaFormatos();
        cargarFormatos();

        menuCerrarSesion.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Cerrar la ventana actual
                dispose();

                // Abrir UILogin
                UILogin login = new UILogin();
                login.setVisible(true);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanelEmpleado = new javax.swing.JPanel();
        jLabelEmpleado = new javax.swing.JLabel();
        jLabelTextoEmpleado = new javax.swing.JLabel();
        jPanelDistribuidorasPeliculas = new javax.swing.JPanel();
        jScrollPaneFormatos = new javax.swing.JScrollPane();
        botonAñadirDisVideojuegos = new javax.swing.JButton();
        tfNuevoFormato = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        botonNuevaPelicula = new javax.swing.JButton();
        botonNuevoSocio = new javax.swing.JButton();
        botonEmpleados = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jPanelDistribuidoras = new javax.swing.JPanel();
        jScrollPaneDistribuidoraPeliculas = new javax.swing.JScrollPane();
        tfNuevaDisPeliculas = new javax.swing.JTextField();
        botonAñadirDisPeliculas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCerrarSesion = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelEmpleado.setBackground(new java.awt.Color(204, 204, 255));
        jPanelEmpleado.setForeground(new java.awt.Color(204, 204, 255));

        jLabelTextoEmpleado.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabelTextoEmpleado.setForeground(new java.awt.Color(51, 153, 255));
        jLabelTextoEmpleado.setText("Area del empleado");

        jScrollPaneFormatos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPaneFormatos.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        botonAñadirDisVideojuegos.setText("Añadir");
        botonAñadirDisVideojuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirDisVideojuegosActionPerformed(evt);
            }
        });

        tfNuevoFormato.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        tfNuevoFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNuevoFormatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDistribuidorasPeliculasLayout = new javax.swing.GroupLayout(jPanelDistribuidorasPeliculas);
        jPanelDistribuidorasPeliculas.setLayout(jPanelDistribuidorasPeliculasLayout);
        jPanelDistribuidorasPeliculasLayout.setHorizontalGroup(
            jPanelDistribuidorasPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDistribuidorasPeliculasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDistribuidorasPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDistribuidorasPeliculasLayout.createSequentialGroup()
                        .addComponent(botonAñadirDisVideojuegos)
                        .addGap(18, 18, 18)
                        .addComponent(tfNuevoFormato, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDistribuidorasPeliculasLayout.createSequentialGroup()
                        .addComponent(jScrollPaneFormatos, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        jPanelDistribuidorasPeliculasLayout.setVerticalGroup(
            jPanelDistribuidorasPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDistribuidorasPeliculasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneFormatos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDistribuidorasPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNuevoFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAñadirDisVideojuegos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CustomRoundedButton customModelFormatos= new CustomRoundedButton();
        customModelFormatos.setNormalColor(new Color(82, 2, 120));
        customModelFormatos.setHoverColor(new Color(25, 231, 255));

        // Crear un botón estándar de Swing

        botonAñadirDisVideojuegos.setModel(customModelFormatos); // Asignar el modelo personalizado

        // Configurar colores dinámicamente con un MouseListener
        botonAñadirDisVideojuegos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                botonAñadirDisVideojuegos.setBackground(customModelFormatos.getHoverColor());
            }

            @Override
            public void mouseExited(MouseEvent e) {
                botonAñadirDisVideojuegos.setBackground(customModelFormatos.getNormalColor());
            }
        });

        // Configurar el botón
        botonAñadirDisVideojuegos.setFocusPainted(false); // Quitar el borde de enfoque
        botonAñadirDisVideojuegos.setBackground(customModelFormatos.getNormalColor()); // Color inicial
        botonAñadirDisVideojuegos.setForeground(Color.WHITE); // Color del texto
        botonAñadirDisVideojuegos.setFont(new Font("Arial", Font.BOLD,16));

        botonNuevaPelicula.setText("Agregar película");
        botonNuevaPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirGestionPeliculasModal(evt);
            }
        });

        botonNuevoSocio.setText("Añadir socio");
        botonNuevoSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirGestionSociosModal(evt);
            }
        });

        botonEmpleados.setText("Empleados");
        botonEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirGestionEmpleadosModal(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonNuevoSocio)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonEmpleados)
                        .addGap(26, 26, 26)
                        .addComponent(botonNuevaPelicula)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevaPelicula)
                    .addComponent(botonEmpleados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonNuevoSocio)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        CustomRoundedButton customModelNuevaPelicula = new CustomRoundedButton();
        customModelNuevaPelicula.setNormalColor(new Color(25, 231, 255));
        customModelNuevaPelicula.setHoverColor(Color.BLACK);

        // Crear un botón estándar de Swing

        botonNuevaPelicula.setModel(customModelNuevaPelicula); // Asignar el modelo personalizado

        // Configurar colores dinámicamente con un MouseListener
        botonNuevaPelicula.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                botonNuevaPelicula.setBackground(customModelNuevaPelicula.getHoverColor());
            }

            @Override
            public void mouseExited(MouseEvent e) {
                botonNuevaPelicula.setBackground(customModelNuevaPelicula.getNormalColor());
            }
        });

        // Configurar el botón
        botonNuevaPelicula.setFocusPainted(false); // Quitar el borde de enfoque
        botonNuevaPelicula.setBackground(customModelNuevaPelicula.getNormalColor()); // Color inicial
        botonNuevaPelicula.setForeground(Color.WHITE); // Color del texto
        botonNuevaPelicula.setFont(new Font("Arial", Font.BOLD,16));
        CustomRoundedButton customModelNuevoSocio = new CustomRoundedButton();
        customModelNuevoSocio.setNormalColor(Color.BLACK);
        customModelNuevoSocio.setHoverColor(Color.GRAY);

        // Crear un botón estándar de Swing

        botonNuevoSocio.setModel(customModelNuevoSocio); // Asignar el modelo personalizado

        // Configurar colores dinámicamente con un MouseListener
        botonNuevoSocio.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                botonNuevoSocio.setBackground(customModelNuevoSocio.getHoverColor());
            }

            @Override
            public void mouseExited(MouseEvent e) {
                botonNuevoSocio.setBackground(customModelNuevoSocio.getNormalColor());
            }
        });

        // Configurar el botón
        botonNuevoSocio.setFocusPainted(false); // Quitar el borde de enfoque
        botonNuevoSocio.setBackground(customModelNuevoSocio.getNormalColor()); // Color inicial
        botonNuevoSocio.setForeground(Color.WHITE); // Color del texto
        botonNuevoSocio.setFont(new Font("Arial", Font.BOLD,16));

        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jScrollPaneDistribuidoraPeliculas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPaneDistribuidoraPeliculas.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        tfNuevaDisPeliculas.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        tfNuevaDisPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNuevaDisPeliculasActionPerformed(evt);
            }
        });

        botonAñadirDisPeliculas.setText("Añadir");
        botonAñadirDisPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirDisPeliculasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDistribuidorasLayout = new javax.swing.GroupLayout(jPanelDistribuidoras);
        jPanelDistribuidoras.setLayout(jPanelDistribuidorasLayout);
        jPanelDistribuidorasLayout.setHorizontalGroup(
            jPanelDistribuidorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDistribuidorasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDistribuidorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneDistribuidoraPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDistribuidorasLayout.createSequentialGroup()
                        .addComponent(botonAñadirDisPeliculas)
                        .addGap(18, 18, 18)
                        .addComponent(tfNuevaDisPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDistribuidorasLayout.setVerticalGroup(
            jPanelDistribuidorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDistribuidorasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneDistribuidoraPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDistribuidorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNuevaDisPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAñadirDisPeliculas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CustomRoundedButton customModelDisPeliculas = new CustomRoundedButton();
        customModelDisPeliculas.setNormalColor(new Color(82, 2, 120));
        customModelDisPeliculas.setHoverColor(new Color(25, 231, 255));

        // Crear un botón estándar de Swing

        botonAñadirDisPeliculas.setModel(customModelDisPeliculas); // Asignar el modelo personalizado

        // Configurar colores dinámicamente con un MouseListener
        botonAñadirDisPeliculas.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                botonAñadirDisPeliculas.setBackground(customModelDisPeliculas.getHoverColor());
            }

            @Override
            public void mouseExited(MouseEvent e) {
                botonAñadirDisPeliculas.setBackground(customModelDisPeliculas.getNormalColor());
            }
        });

        // Configurar el botón
        botonAñadirDisPeliculas.setFocusPainted(false); // Quitar el borde de enfoque
        botonAñadirDisPeliculas.setBackground(customModelDisPeliculas.getNormalColor()); // Color inicial
        botonAñadirDisPeliculas.setForeground(Color.WHITE); // Color del texto
        botonAñadirDisPeliculas.setFont(new Font("Arial", Font.BOLD,16));

        javax.swing.GroupLayout jPanelEmpleadoLayout = new javax.swing.GroupLayout(jPanelEmpleado);
        jPanelEmpleado.setLayout(jPanelEmpleadoLayout);
        jPanelEmpleadoLayout.setHorizontalGroup(
            jPanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEmpleadoLayout.createSequentialGroup()
                .addGroup(jPanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelEmpleadoLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabelTextoEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRefresh)
                        .addGap(9, 9, 9))
                    .addGroup(jPanelEmpleadoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelEmpleadoLayout.createSequentialGroup()
                                .addComponent(jPanelDistribuidorasPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelDistribuidoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanelEmpleadoLayout.setVerticalGroup(
            jPanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEmpleadoLayout.createSequentialGroup()
                            .addComponent(jLabelTextoEmpleado)
                            .addGap(28, 28, 28)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEmpleadoLayout.createSequentialGroup()
                        .addComponent(jButtonRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDistribuidorasPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDistribuidoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDistribuidorasPeliculas.setOpaque(false);
        jPanel1.setOpaque(false);
        CustomRoundedButton customModelActualizar = new CustomRoundedButton();
        customModelActualizar.setNormalColor(Color.GRAY);
        customModelActualizar.setHoverColor(Color.BLACK);

        // Crear un botón estándar de Swing

        jButtonRefresh.setModel(customModelActualizar); // Asignar el modelo personalizado

        // Configurar colores dinámicamente con un MouseListener
        jButtonRefresh.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                jButtonRefresh.setBackground(customModelActualizar.getHoverColor());
            }

            @Override
            public void mouseExited(MouseEvent e) {
                jButtonRefresh.setBackground(customModelActualizar.getNormalColor());
            }
        });

        // Configurar el botón
        jButtonRefresh.setFocusPainted(false); // Quitar el borde de enfoque
        jButtonRefresh.setBackground(customModelActualizar.getNormalColor()); // Color inicial
        jButtonRefresh.setForeground(Color.WHITE); // Color del texto
        jButtonRefresh.setFont(new Font("Arial", Font.BOLD,16));
        jPanelDistribuidoras.setOpaque(false);

        jMenu1.setText("Opciones");

        menuCerrarSesion.setText("Cerrar sesión");
        jMenu1.add(menuCerrarSesion);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Inicializar tabla para mostrar distribuidoras
    private void inicializarTablaDistribuidorasPeliculas() {
        modeloTablaDistribuidorasPeliculas = new DefaultTableModel(new String[]{"ID", "Nombre"}, 0);
        tablaDistribuidorasPeliculas = new JTable(modeloTablaDistribuidorasPeliculas);
        jScrollPaneDistribuidoraPeliculas.setViewportView(tablaDistribuidorasPeliculas);
    }

    // Cargar distribuidoras desde la base de datos y mostrarlas en la tabla
    private void cargarDistribuidorasPeliculas() {
        try ( Connection conn = Database.getConnection()) {
            List<DistribuidoraPeliculas> distribuidoras = DistribuidoraPeliculas.consultarDistribuidorasPeliculas(conn);
            modeloTablaDistribuidorasPeliculas.setRowCount(0);  // Limpiar tabla antes de agregar
            for (DistribuidoraPeliculas d : distribuidoras) {
                modeloTablaDistribuidorasPeliculas.addRow(new Object[]{d.getId(), d.getNombre()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar distribuidoras: " + ex.getMessage());
        }
    }

    private void inicializarTablaFormatos() {
        modeloTablaFormatos = new DefaultTableModel(new String[]{"ID", "Nombre", "Cantidad"}, 0);
        tablaFormatos = new JTable(modeloTablaFormatos);
        jScrollPaneFormatos.setViewportView(tablaFormatos);
    }

    private void cargarFormatos() {
        List<Formato> formatos = Formato.obtenerFormatos();
        modeloTablaFormatos.setRowCount(0); // Limpiar la tabla antes de agregar datos

        for (Formato formato : formatos) {
            modeloTablaFormatos.addRow(new Object[]{
                formato.getId(),
                formato.getNombre(),
                formato.getCantidadProductos()
            });
        }
    }

    private void agregarFormatos() {
        String nombreFormato = tfNuevoFormato.getText().trim();  // Obtener el texto del campo de texto
        if (!nombreFormato.isEmpty()) {
            try ( Connection conn = Database.getConnection()) {  // Establecer la conexión
                // Llamar al método agregarFormato
                Formato.agregarFormato(conn, nombreFormato);
                cargarFormatos();  // Recargar lista de formatos
                tfNuevoFormato.setText("");  // Limpiar el campo de texto
                JOptionPane.showMessageDialog(this, "Formato agregado con éxito.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al agregar formato: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del formato.");
        }
    }

    // Cargar distribuidoras desde la base de datos y mostrarlas en la tabla
//    private void cargarDistribuidorasVideojuegos() {
//        try (Connection conn = Database.getConnection()) {
//            List<DistribuidoraVideojuegos> distribuidoras = DistribuidoraVideojuegos.consultarDistribuidorasVideojuegos(conn);
//            modeloTablaDistribuidorasVideojuegos.setRowCount(0);  // Limpiar tabla antes de agregar
//            for (DistribuidoraVideojuegos d : distribuidoras) {
//                modeloTablaDistribuidorasVideojuegos.addRow(new Object[]{d.getId(), d.getNombre()});
//            }
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(this, "Error al cargar distribuidoras: " + ex.getMessage());
//        }
//    }
    // Agregar una nueva distribuidora al presionar el botón Añadir
    private void agregarDistribuidoraPeliculas() {
        String nombreDistribuidora = tfNuevaDisPeliculas.getText().trim();
        if (!nombreDistribuidora.isEmpty()) {
            try ( Connection conn = Database.getConnection()) {
                DistribuidoraPeliculas.agregarDistribuidoraPeliculas(conn, nombreDistribuidora);
                cargarDistribuidorasPeliculas();  // Recargar lista
                tfNuevaDisPeliculas.setText("");  // Limpiar campo
                JOptionPane.showMessageDialog(this, "Distribuidora agregada con éxito.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al agregar distribuidora: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre de la distribuidora.");
        }
    }

    private void tfNuevaDisPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNuevaDisPeliculasActionPerformed
        agregarDistribuidoraPeliculas();
    }//GEN-LAST:event_tfNuevaDisPeliculasActionPerformed

    private void botonAñadirDisPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirDisPeliculasActionPerformed
        agregarDistribuidoraPeliculas();
    }//GEN-LAST:event_botonAñadirDisPeliculasActionPerformed

    private void abrirGestionPeliculasModal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirGestionPeliculasModal
        GestionPeliculas gestionPeliculas = new GestionPeliculas();
        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Gestión de Películas", true);
        dialog.setContentPane(gestionPeliculas.getContentPane());
        dialog.pack();
        dialog.setLocationRelativeTo(this);  // Centrar sobre la ventana principal
        dialog.setVisible(true);  // Mostrar modal
    }//GEN-LAST:event_abrirGestionPeliculasModal

    private void abrirGestionEmpleadosModal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirGestionEmpleadosModal
        GestionEmpleados gestionEmpleados = new GestionEmpleados();
        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Gestión de Empleados", true);
        dialog.setContentPane(gestionEmpleados.getContentPane());
        dialog.pack();
        dialog.setLocationRelativeTo(this);  // Centrar sobre la ventana principal
        dialog.setVisible(true);  // Mostrar modal
    }//GEN-LAST:event_abrirGestionEmpleadosModal

//        private void abrirGestionSociosModal(java.awt.event.ActionEvent evt) {                                            
//        GestionSocios gestionSocios = new GestionSocios();
//        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Nuevo Socio", true);
//        dialog.setContentPane(gestionSocios.getContentPane());
//        dialog.pack();
//        dialog.setLocationRelativeTo(this);  // Centrar sobre la ventana principal
//        dialog.setVisible(true);  // Mostrar modal
//    }       
    // Agregar una nueva distribuidora al presionar el botón Añadir
    private void agregarDistribuidoraVideojuegos() {
        String nombreDistribuidora = tfNuevoFormato.getText().trim();
        if (!nombreDistribuidora.isEmpty()) {
            try ( Connection conn = Database.getConnection()) {
                DistribuidoraVideojuegos.agregarDistribuidoraVideojuegos(conn, nombreDistribuidora);
                cargarDistribuidorasPeliculas();  // Recargar lista
                tfNuevoFormato.setText("");  // Limpiar campo
                JOptionPane.showMessageDialog(this, "Distribuidora agregada con éxito.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al agregar distribuidora: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre de la distribuidora.");
        }
    }

    private void tfNuevoFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNuevoFormatoActionPerformed
        agregarDistribuidoraVideojuegos();
    }//GEN-LAST:event_tfNuevoFormatoActionPerformed

    private void botonAñadirDisVideojuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirDisVideojuegosActionPerformed
        agregarFormatos();
    }//GEN-LAST:event_botonAñadirDisVideojuegosActionPerformed

    private void abrirGestionSociosModal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirGestionSociosModal
        GestionSocios gestionSocios = new GestionSocios();
        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Nuevo Socio", true);
        dialog.setContentPane(gestionSocios.getContentPane());
        dialog.pack();
        dialog.setLocationRelativeTo(this);  // Centrar sobre la ventana principal
        dialog.setVisible(true);  // Mostrar modal
    }//GEN-LAST:event_abrirGestionSociosModal

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        cargarFormatos();
    }//GEN-LAST:event_jButtonRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadirDisPeliculas;
    private javax.swing.JButton botonAñadirDisVideojuegos;
    private javax.swing.JButton botonEmpleados;
    private javax.swing.JButton botonNuevaPelicula;
    private javax.swing.JButton botonNuevoSocio;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabelEmpleado;
    private javax.swing.JLabel jLabelTextoEmpleado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDistribuidoras;
    private javax.swing.JPanel jPanelDistribuidorasPeliculas;
    private javax.swing.JPanel jPanelEmpleado;
    private javax.swing.JScrollPane jScrollPaneDistribuidoraPeliculas;
    private javax.swing.JScrollPane jScrollPaneFormatos;
    private javax.swing.JMenuItem menuCerrarSesion;
    private javax.swing.JTextField tfNuevaDisPeliculas;
    private javax.swing.JTextField tfNuevoFormato;
    // End of variables declaration//GEN-END:variables
}
